#!/usr/bin/env python
import sys
import rospy
import json

from _openccg import OpenCCG
from _xml_parser import XMLReader

from std_msgs.msg import String

import xml.etree.ElementTree as ET

publisher = None
parser = None

def callback(msg):
  result = String()
  parses = parser.parse(msg.data)

  intents = []

  for parse in parses:
    intent = XMLReader.read(ET.fromstring(parse))
    if intent:
      intents.append(intent.toJSON())

  result.data = json.dumps({'utterance': msg.data, 'intents': intents, 'parses': parses})

  publisher.publish(result)

def main():
  try:
    global publisher, parser

    rospy.init_node('openccg')

    parser = OpenCCG(rospy.get_param('~grammar', None))
    parser.connect()

    rospy.Subscriber('/speech', String, callback)
    publisher = rospy.Publisher('/speech/parses', String, queue_size=5)

    rospy.spin()

  except Exception as e:
    rospy.logerr(str(e))
    sys.exit(1)

if __name__ == '__main__':
  main()
